name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - master
env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ${{env.CACHED_DEPENDENCY_PATHS}}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run lint
      - run: npm run build
